### ISSUE TITLE
openai 답변 완성하기

### ISSUE THREAD

**Issue by crazywook** [crazywook/openai-template#1]
### 문제점
한번에 답변이 다 오지 않는다.
```javascript
[
    {
      text: '\n\nIf you are looking to use the OpenAI API to develop your own',
      index: 0,
      logprobs: null,
      finish_reason: 'length'
    }
]
```
### 접근
finish_reason이 length인걸로 봐서 문장을 이어 붙여서 보내봤더니 추가적으로 계속 문장을 완선해주고 끝에 finish_reason이 stop 이 된다.

### TODO
- [x] 재귀적으로 문장으로 이어 붙여서 stop이 나올 때까지 진행하기
- [x] davinci-002 으로 해보기
- [ ] davinci-003 으로 해보기

**Comment by crazywook** [comment]
### DONE
재귀적으로 답변 붙여서 받는 것 까지는 성공했다.

### NEXT
- [ ] davinci-003 은 요청이 많아서 그런지 정상 작동하지 않은 경우가 많다.
- [ ] 무료 API는 요청횟수 제한이 있다.
  Limit: 60.000000 / min. Current: 70.000000
  해당 limit을 안넘도록 제어하는 것이 필요하다.
